apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: app-database
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306  # Corrigido para a porta do MySQL
      envFrom:
        - configMapRef:
            name: database-config