apiVersion: v1
kind: Pod
metadata:
  name: meu-pod
  labels:
    app: http-echo
spec:
  containers:
    - name: http-echo-container
      image: hashicorp/http-echo:latest
      args:
        - "-text=Olá, Kubernetes!"
      ports:
        - containerPort: 81
