apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: http-echo
  ports:
    - port: 80 #ouve na porta 80
      targetPort: 5678 #redireciona para a porta do serviço
      nodePort: 30000 #aplicações externas se comunicam pela porta 30000 com o node