apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-declarativo
  labels:
    app: app-pod-1
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      ports:
        - containerPort: 80