apiVersion: v1
kind: Service
metadata:
  name: svc-sistema
spec:
  type: NodePort
  selector:
    app: app-sistema
  ports:
    - port: 80 #ouve na porta 80
      nodePort: 30001 #aplicações externas se comunicam pela porta 30000 com o node