apiVersion: v1
kind: Pod
metadata:
  name: sistema-pod
  labels:
    app: app-sistema
spec:
  containers:
    - name: sistema-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-config